spring.application.name=Code-Review-Assistant-AI

server.port=8087

#spring.datasource.url=jdbc:mysql://localhost:3306/AicodeReview
#spring.datasource.username=root
#spring.datasource.password=Prashu@2004
#
#spring.jpa.hibernate.ddl-auto=update

openai.api.key=${API_KEY}