spring.application.name=Code-Review-Assistant-AI

server.port=8087

#spring.datasource.url=jdbc:mysql://localhost:3306/AicodeReview
#spring.datasource.username=root
#spring.datasource.password=Prashu@2004
#
#spring.jpa.hibernate.ddl-auto=update

openai.api.key=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
